version: "3.3"

services:

  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - ./api:/api/src/app
      - /api/src/app/node_modules/
    command: npm run start
    depends_on:
      - postgres
    environment:
      PORT: 3000
    env_file:
      - ./.env
    ports:
      - 3000:3000
      - 9229:9229

  frontend:
    depends_on:
      - api
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - ./frontend:/frontend/src/app
      - /frontend/src/app/node_modules
    command: npm run start
    environment:
      PORT: 4200
    ports:
      - 4200:4200
    links:
      - api

  postgres:
    image: postgres:15.4
    env_file:
      - ./.env
    ports:
      - 35000:5432

  postgres_admin:
    image: dpage/pgadmin4:7.7
    depends_on:
      - postgres
    env_file:
      - ./.env
    ports:
      - 5050:80
